<?php

namespace AppBundle\Repository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAbandonedBasketsDayBefore()
    {
        $qb = $this->createQueryBuilder('b')
            ->Where('b.updatedAt BETWEEN :start AND :end')
            ->setParameter('start', new \Datetime("yesterday"))
            ->setParameter('end', new \Datetime("today"))
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
